server:
  port: 9011
spring:
  application:
    name: stock-server
  cloud:
    nacos:
      config:
#        enabled: false
        refresh-enabled: false
      discovery:
#        enabled: false
        server-addr: 192.168.190.129:8848
        username: nacos
        password: nacos
